services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  config-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config_service
    command: bash -c "java -jar /app/config-service/build/libs/config-service-1.0-SNAPSHOT.jar"
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8888:8888"

  discovery-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discovery-service
    command: bash -c "sleep 15 && java -jar /app/discovery-service/build/libs/discovery-service-1.0-SNAPSHOT.jar"
    restart: on-failure
    depends_on:
      - config-service
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_service
    command: bash -c "sleep 30 && java -jar /app/gateway-service/build/libs/gateway-service-1.0-SNAPSHOT.jar"
    restart: on-failure
    depends_on:
      - discovery-service
    ports:
      - "8765:8765"

  cart-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cart-service
    command: bash -c "sleep 30 && java -jar /app/cart-service/build/libs/cart-service-1.0-SNAPSHOT.jar"
    restart: on-failure
    depends_on:
      - gateway-service
    ports:
      - "8082:8082"
#    healthcheck:
#      test: curl --fail http://localhost:8082/carts/ping || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 40s
#      timeout: 10s

  consumer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer-service
    command: bash -c "sleep 30 && java -jar /app/consumer-service/build/libs/consumer-service-1.0-SNAPSHOT.jar"
    restart: on-failure
    depends_on:
      - gateway-service
    ports:
      - "8085:8085"
#    healthcheck:
#      test: curl --fail http://localhost:8085/consumers/ping || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 40s
#      timeout: 10s

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    command: bash -c "sleep 30 && java -jar /app/product-service/build/libs/product-service-1.0-SNAPSHOT.jar"
    restart: on-failure
    depends_on:
      - gateway-service
    ports:
      - "8081:8081"
#    healthcheck:
#      test: curl --fail http://localhost:8081/products/ping || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 40s
#      timeout: 10s

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    command: bash -c "sleep 30 && java -jar /app/order-service/build/libs/order-service-1.0-SNAPSHOT.jar"
    restart: on-failure
    depends_on:
      - gateway-service
    ports:
      - "8083:8083"
#    healthcheck:
#      test: curl --fail http://localhost:8083/orders/ping || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 40s
#      timeout: 10s


volumes:
  postgres_data:
