services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  config-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config_service
    command: java -jar /app/config-service.jar
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8888:8888"
    mem_limit: 512m

  discovery-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discovery-service
    command: java -jar /app/discovery-service.jar
    restart: unless-stopped
    depends_on:
      - config-service
    ports:
      - "8761:8761"
    mem_limit: 512m

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_service
    command: java -jar /app/gateway-service.jar
    restart: unless-stopped
    depends_on:
      - discovery-service
    ports:
      - "8765:8765"
    mem_limit: 512m

  cart-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cart-service
    command: java -jar /app/cart-service.jar
    restart: unless-stopped
    depends_on:
      - gateway-service
    ports:
      - "8082:8082"
    mem_limit: 512m

  consumer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer-service
    command: java -jar /app/consumer-service.jar
    restart: unless-stopped
    depends_on:
      - gateway-service
    ports:
      - "8085:8085"
    mem_limit: 512m

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    command: java -jar /app/product-service.jar
    restart: unless-stopped
    depends_on:
      - gateway-service
    ports:
      - "8081:8081"
    mem_limit: 512m

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    command: java -jar /app/order-service.jar
    restart: unless-stopped
    depends_on:
      - gateway-service
    ports:
      - "8083:8083"
    mem_limit: 512m


volumes:
  postgres_data:
