spring:
  main:
    allow-bean-definition-overriding: true

security:
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expirationMilliseconds: 300000
    secret: secretKey

server:
  servlet:
    context-path: /auth
  port: ${AUTH_SERVICE_PORT}