hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    product-service:
      path: /products/**
      serviceId: product-service
      stripPrefix: false

    cart-service:
      path: /carts/**
      serviceId: cart-service
      stripPrefix: false

    order-service:
      path: /orders/**
      serviceId: order-service
      stripPrefix: false

    consumer-server:
      path: /consumers/**
      serviceId: consumer-service
      stripPrefix: false

server:
  port: 8765
