spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/product_service_database
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /products
  port: 8081

documentation:
  base-url: http://localhost:8080/products

kafka:
  bootstrap-servers: localhost:9092
  consumer-group:
    order-clothes: order-clothes
  topic:
    consumer:
      order-clothes-topic: order-clothes-topic