spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  profiles:
    active:  native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}
      username: ${CONFIG_SERVICE_USER}

server:
  port: ${CONFIG_SERVICE_PORT}